# base image
FROM node:8.5.0

# set working directory
RUN mkdir /usr/src/api
WORKDIR /usr/src/api

# add `/usr/src/api/node_modules/.bin` to $PATH
ENV PATH /usr/src/api/node_modules/.bin:$PATH

# install and cache app dependencies
ADD package.json /usr/src/api/package.json
RUN npm install --silent
RUN npm install react-scripts@0.1.0 -g --silent
ADD . /usr/src/api

# start app
CMD ["npm", "start"]